apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - database/brain-pg.yaml
  - apps/sealai-api-staging.yaml
  - apps/sealai-ui-staging.yaml
  - apps/sealai-registry.yaml
  - apps/whodb.yaml

