apiVersion: example.crossplane.io/v1
kind: AP
metadata:
  name: fixed-replicas-nginx
  namespace: ns-admin
  labels:
    region: 192.168.12.53.nip.io
spec:
  crossplane:
    compositionRef:
      name: aps-deployment-ingress-go-templating
  projectName: demo-project
  name: fixed-replicas-nginx
  input:
    image: nginx:1.27
    network:
      privatePort: 80
  resource:
    replicaStrategy:
      type: fixed
      fixed:
        replicas: 2
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi
