apiVersion: example.crossplane.io/v1
kind: AP
metadata:
  name: memory-elastic-nginx
  namespace: ns-admin
  labels:
    region: 192.168.12.53.nip.io
spec:
  crossplane:
    compositionRef:
      name: aps-deployment-ingress-go-templating
  projectName: demo-project
  name: memory-elastic-nginx
  input:
    image: nginx:1.27
    network:
      privatePort: 80
  resource:
    replicaStrategy:
      type: elastic
      elastic:
        minReplicas: 2
        maxReplicas: 8
        target:
          metric: memory
          type: averageValue
          averageValue: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi
