apiVersion: example.crossplane.io/v1
kind: Project
metadata:
  name: demo-project
  namespace: ns-admin
spec:
  crossplane:
    compositionRef:
      name: project-instance-go-templating
  public: false
