apiVersion: example.crossplane.io/v1
kind: DB
metadata:
  name: db-postgresql
  namespace: ns-admin
  labels:
    region: 192.168.12.53.nip.io
spec:
  crossplane:
    compositionRef:
      name: dbs-postgresql-kubeblocks-go-templating
  engine: postgresql
  # exposeNodePort: true
  quota: xs
