apiVersion: v1
kind: Secret
metadata:
  name: ghcr-cred
  namespace: brain-system
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"github-user","password":"github-token","auth":"base64-user-colon-token"}}}'

